Lamda Numpy Panda

In [22]:
import numpy as np
#All 0's Matrix
a=np.zeros((2,3))
print(a)
#All 1's Matrix
b=np.ones((2,3,3),dtype='int')
print(b)
#Any other number
c=np.full((2,2),99)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
[[99 99]
 [99 99]]
